[package]
name = "kavod"
version = "0.0.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "An algorithmic backtesting & trading library"
repository = "https://github.com/Tacivus/kavod"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
serde_json = { version = "1", features = ["raw_value"] }
trybuild = "1"
